### PR TITLE
Final Merge edits

### PR DESCRIPTION
**Pull request by RahulAdityaMani**

### CODE REVIEW

**Comment by RahulAdityaMani** [comment]
Hi sorry here are some final changes

**Comment by isoboroff** [comment]
We shouldn't have to include specific jars, we should be able to add the dependencies to the pom.xml file.  Do you know how to do that?

Sorry to be communicating through github today... it's been meeting-tastical.  I will catch up face-to-face before you're off for the Robotics competition.

**Comment by RahulAdityaMani** [comment]
It's fine @isoboroff 👍 . I can remove the JARS. The main edits involved the SearchServer, EntityTypeRenderer, and SearchSetup java files. I can do some research on how to add the dependencies to the pom.xml and I'll get back in touch if I have any difficulties.

**Comment by isoboroff** [comment]
I always get the XML snippet from mvnrepository, for example https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core/2.7.5

**Comment by RahulAdityaMani** [comment]
Done (I hope) 😎

**Pull request merged**
