### PR TITLE
My changes so far

### PR DESCRIPTION
**Pull request by RahulAdityaMani**
Adjusted Attributes Order For All Entities
Added JSON output for context hashmap
Allowed for printing of context hashmap in JSON format to console

### CODE REVIEW

**Comment by isoboroff** [comment]
The changes in SearchServer duplicate a lot of code from the search/ endpoint.  Maybe it's better to separate out that code into a new function?

The JSON output should go back to the browser, not out to a file.

Can you fix these two things?

**Comment by RahulAdityaMani** [comment]
sure. I'm on it

**Comment by RahulAdityaMani** [comment]
Is that what you meant by sending the JSON output to the browser?

**Comment by RahulAdityaMani** [comment]
screen shot 2016-06-29 at 11 49 03 am
This is what shows up when something is searched for

**Comment by isoboroff** [comment]
Yes.  It'll be unreadable to you or me, but perfectly usable by software on
the other side.  It's like they would want to replace our front end (the
Pebble template), so we do all the processing up to that point.

**Comment by RahulAdityaMani** [comment]
I finished creating the function you were talking about earlier, and the program still seems to be working, which is good. 👍

**Comment by RahulAdityaMani** [comment]
I made a separate class for setting up the search in order to further clean up the code. I think it's working, but on a couple of occasions I've gotten random errors that seem to clear up once I refresh the search engine or the page I'm on, so perhaps they were just fluky bugs or something. Let me know what you think, or whether any modifications/changes need to be made. Thanks.

**Comment by isoboroff** [comment]
Much better.  I have a couple things I'd like to change, but for now, can you pull the current changes to your tree and resolve the merge conflicts?  Then this should be mergeable, and then I can show you some things I would do differently.

**Comment by RahulAdityaMani** [comment]
Will do. Thanks

**Pull request merged**
